Task 1.2
vitek2711/itstep pull request #3
Opened 2021-11-13 19:29 UTC by vitek2711

Созданы страницы: Главная, каталог, контакты.

- На странице "Главная" добавлено описание, название, меню и копирайт.

- На странице "Каталог" добавлены изображения товаров и ссылки с переходом на соответствующую позицию товара. Добавлено главное меню.

- На странице "Контакты" добавлено главное меню, копирайт, контактные данные и форма обратной связи.

2021-11-14 07:27 UTC, itstep-mog requested changes
Требуются исправления по коду

2021-11-14 07:27 UTC, itstep-mog commented on footballmarkt/adidas-copa.html
> +<h3>Подробное описание товара</h3>
Чем данный заголовок, по смысловому содержанию отличается от заголовков в строках 23 и 25? Почему в одном случае используется `<h2>`, а в строке 34 используется` <h3>`?

2021-11-14 07:27 UTC, itstep-mog commented on footballmarkt/adidas-copa.html
> +    <li><a href="./contacts.html">Наши контакты</a></li>
Элементы данного списка должны быть помещены в тег `<ul>` или `<ol>` и не должны использоваться самостоятельно.

2021-11-14 07:27 UTC, itstep-mog commented on footballmarkt/contacts.html
> +    <li><a href="#">Наши контакты</a></li>
Элементы данного списка должны быть помещены в тег `<ul>` или `<ol>` и не должны использоваться самостоятельно.

2021-11-14 07:27 UTC, itstep-mog commented on footballmarkt/contacts.html
> +<h3>Наш адрес:</h3>
Это тег `<p>`

2021-11-14 07:27 UTC, itstep-mog commented on footballmarkt/contacts.html
> +            <p><input checked type="checkbox" value="yes">Я согласен с правилами магазина</p>
В данном случае нужен тег `<lable>`

2021-11-14 07:27 UTC, itstep-mog commented on footballmarkt/index.html
> +пердствлена вся линейка товаров, как для любителей, так и профессионалов.
Без обвертки не стоит использовать текст. Помести его в тег `<p>`

2021-11-14 07:27 UTC, itstep-mog commented on footballmarkt/nike-merkurial.html
> +<li><a href="./contacts.html">Наши контакты</a></li>
Элементы данного списка должны быть помещены в тег `<ul>` или `<ol>` и не должны использоваться самостоятельно.

2021-11-14 07:27 UTC, itstep-mog commented on footballmarkt/nike-phantom.html
> +    <li><a href="./contacts.html">Наши контакты</a></li>
Элементы данного списка должны быть помещены в тег `<ul>` или `<ol>` и не должны использоваться самостоятельно.

2021-11-14 07:27 UTC, itstep-mog commented on footballmarkt/nike-phantom.html
> +<h3>Подробное описание товара</h3>
Чем данный заголовок, по смысловому содержанию отличается от заголовков в строках 23 и 25? Почему в одном случае используется `<h2>`, а в строке 34 используется `<h3>`?

2021-11-16 18:34 UTC, vitek2711 commented on footballmarkt/adidas-copa.html
> +    <li><a href="./contacts.html">Наши контакты</a></li>
has been fixed

2021-11-16 18:34 UTC, vitek2711 commented on footballmarkt/contacts.html
> +    <li><a href="#">Наши контакты</a></li>
has been fixed

2021-11-16 18:34 UTC, vitek2711 commented on footballmarkt/contacts.html
> +<h3>Наш адрес:</h3>
has been fixed

2021-11-16 18:34 UTC, vitek2711 commented on footballmarkt/contacts.html
> +            <p><input checked type="checkbox" value="yes">Я согласен с правилами магазина</p>
has been fixed

2021-11-16 18:34 UTC, vitek2711 commented on footballmarkt/index.html
> +пердствлена вся линейка товаров, как для любителей, так и профессионалов.
has been fixed

2021-11-16 18:34 UTC, vitek2711 commented on footballmarkt/nike-merkurial.html
> +<li><a href="./contacts.html">Наши контакты</a></li>
has been fixed

2021-11-16 18:34 UTC, vitek2711 commented on footballmarkt/nike-phantom.html
> +    <li><a href="./contacts.html">Наши контакты</a></li>
has been fixed

2021-11-16 18:34 UTC, vitek2711 commented on footballmarkt/nike-phantom.html
> +<h3>Подробное описание товара</h3>
has been fixed

2021-11-16 18:37 UTC, merged